plugins:
 - rubocop-sorbet
 - rubocop-minitest

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
  - "vendor/**/*"
  - "test/fixtures/**/*"
  - "bin/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
