Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
