# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `StaticsController`.
# Please instead update this file by running `bin/tapioca dsl StaticsController`.

class StaticsController
  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::ActionController::Base::HelperMethods
    include ::ApplicationHelper
    include ::PostsHelper
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
